name: weli
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  #  state management
  flutter_bloc: ^8.0.1
  #  api request
  dio: ^5.4.0
  #  object compare
  equatable: ^2.0.3
  #  international
  intl: ^0.18.1
  intl_utils: ^2.6.1
  #  logging
  logger: ^2.0.2+1
  #  storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.13
  #  firebase
  firebase_storage: ^11.5.4
  firebase_core: ^2.24.1
  cloud_firestore: ^4.13.4
  firebase_messaging: ^14.7.7
  firebase_auth: ^4.15.1
  firebase_crashlytics: ^3.4.7
  flutter_local_notifications: ^16.2.0
  #  cache image
  cached_network_image: ^3.2.0
  #  di
  get_it: ^7.2.0
  #  svg render
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  json_annotation: ^4.4.0
  #  icon
  ionicons: ^0.2.2
  font_awesome_flutter: any
  #  tinder-like card
  tcard: ^1.3.5
  #  form
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  #  responsive
  sizer: any
  #  show toast
  fluttertoast: ^8.0.9
  #  show loading
  flutter_easyloading: ^3.0.3
  #  pick image
  image_picker: ^1.0.4
  #  type ahead form
  flutter_typeahead: ^5.0.1
  #  number input with increase, decrease
  number_inc_dec: ^0.8.0
  #  list, map, set method
  collection: any
  #  carousel effect
  carousel_slider: ^4.0.0
  #  loading animations
  flutter_spinkit: ^5.1.0
  #  format text input
  mask_text_input_formatter: ^2.3.0
  #  lazy loading
  pull_to_refresh: ^2.0.0
  # launch url
  url_launcher: ^6.0.20

  flutter_launcher_icons: ^0.13.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/graphics/
    - assets/graphics/icons/
    - assets/graphics/card/
    - assets/graphics/icons/bar/
    - assets/graphics/icons/nav-bar/
    - assets/icon/
    - assets/fonts/AppIcons.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

flutter_intl:
  enabled: true
